apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-book
spec:
  replicas: 2
  selector:
    matchLabels:
      app: address-book
  template:
    metadata:
      labels:
        app: address-book
    spec:
      containers:
      - name: address-book
        image: aliabsv/addressbook:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: address-book
spec:
  type: NodePort
  selector:
    app: address-book
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30001
    
